services:
  netdash:
      build: .
      image: netdash:latest
      container_name: netdash
      restart: unless-stopped
      privileged: true
      network_mode: host
      cap_add:
        - NET_ADMIN
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./speedtest_history.json:/app/speedtest_history.json
